server:
  port: 8082
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stock?useUnicode=true&characterEncoding=utf8
        username: root
#        password: 123123
    application:
      name: stock-service

mybatis:
  type-aliases-package: com.raincat.dubbo.sample.stock.api.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
    level:
        root: info
    path: "./logs"


